name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
      
    - name: Archive the Jar
      uses: actions/upload-artifact@v4
      with:
        name: Java_Addition_CICD
        path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: Java_Addition_CICD

    - name: Deploy Artifacts
      run: |
        echo "Deploying artifacts..."
        # Add your deployment commands, e.g., uploading to a server or cloud
        # Example: scp target/*.jar user@server:/path/to/deploy
